#!/usr/bin/env sh

echo "Copying windows terminal settings..."

SETTINGS="/home/kade/dotfiles/windows-terminal/settings.json"
DESTINATION="/mnt/c/Users/kade.allen/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/"

mv "$SETTINGS" "$DESTINATION"
