import = [
	# "~/.config/alacritty/themes/themes/hardhacker.toml"
	# "~/.config/alacritty/themes/themes/carbonfox.toml"
	# "~/.config/alacritty/themes/themes/nord.toml"
	"~/.config/alacritty/rose-pine.toml"
	# "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"

]
[font]
size = 14.0
offset = { y = 6 }
normal = { family = "FiraMono Nerd Font", style = "Regular"}

[env]
term = "xterm-256color"

[keyboard]
bindings = [
	{ key = "Key6", mods = "Control", chars = "\u001e" }
]

[window]
dimensions = { columns = 100, lines = 30 }
padding = {x = 5, y = 0}
decorations = "Buttonless"
option_as_alt = "OnlyLeft"

[cursor]
style = { shape = "Beam", blinking = "On"}
