return {
  -- {
  -- '3rd/image.nvim',
  -- dependencies = {
  --   'vhyrro/luarocks.nvim',
  -- },
  -- config = function()
  --   package.path = package.path .. ';' .. vim.fn.expand '$HOME' .. '/.luarocks/share/lua/5.1/?/init.lua'
  --   package.path = package.path .. ';' .. vim.fn.expand '$HOME' .. '/.luarocks/share/lua/5.1/?.lua'
  --   require('image').setup {
  --     backend = 'kitty',
  --     max_width = 100,
  --     max_height = 12,
  --     max_height_window_percentage = math.huge,
  --     max_width_window_percentage = math.huge,
  --     window_overlap_clear_enabled = true,
  --     window_overlap_clear_ft_ignore = { 'cmp_menu', 'cmp_docs', '' },
  --   }
  -- end,
  -- },
}
